DROP TABLE JOB_CONTROL;
DROP TABLE RESTART_CONTROL;
DROP TABLE JOB_RESULT;
DROP TABLE ADDRESS;

CREATE TABLE SALES (
    ID          INTEGER NOT NULL,
    ITEM        VARCHAR(50),
    PRICE       INTEGER,
    CUSTOMER    VARCHAR(50)
)

INSERT INTO SALES(ID, ITEM, PRICE, CUSTOMER) VALUES ('1', 'iPod', '20000', 'yamada');
INSERT INTO SALES(ID, ITEM, PRICE, CUSTOMER) VALUES ('2', 'iPod', '20000', 'takahashi');
INSERT INTO SALES(ID, ITEM, PRICE, CUSTOMER) VALUES ('3', 'iPod', '20000', 'suzuki');
INSERT INTO SALES(ID, ITEM, PRICE, CUSTOMER) VALUES ('4', 'walkman', '25000', 'yamada');
INSERT INTO SALES(ID, ITEM, PRICE, CUSTOMER) VALUES ('5', 'walkman', '25000', 'kuroda');
INSERT INTO SALES(ID, ITEM, PRICE, CUSTOMER) VALUES ('6', 'macbook', '100000', 'tanaka');
INSERT INTO SALES(ID, ITEM, PRICE, CUSTOMER) VALUES ('7', 'vaio', '120000', 'iwakuma');

-- 
-- �W���u�Ǘ��e�[�u��
-- 
CREATE TABLE JOB_CONTROL (
	REQUEST_NO     VARCHAR(20) NOT NULL,
	JOB_ID         VARCHAR(20),
	JOB_FILE       VARCHAR(100),
	PARAMETER      VARCHAR(120),
	STATE          CHAR(1),
	END_CODE       VARCHAR(5),
	START_TIME     TIMESTAMP,
	UPDATE_TIME    TIMESTAMP,
	REGISTER_TIME  TIMESTAMP,
	PRIMARY KEY(REQUEST_NO)
);


-- 
-- ���X�^�[�g�Ǘ��e�[�u��
-- 
CREATE TABLE RESTART_CONTROL (
	REQUEST_NO     VARCHAR(20) NOT NULL,
	JOB_ID         VARCHAR(20) NOT NULL,
	PARTITION_NO   VARCHAR(20) NOT NULL,
	PARTITION_KEY  VARCHAR(30),
	RESTART_POINT  numeric(30),
	JOB_CONTEXT    bytea,
	STATE          CHAR(1),
	UPDATE_TIME    TIMESTAMP,
	REGISTER_TIME  TIMESTAMP,
	PRIMARY KEY(REQUEST_NO,JOB_ID,PARTITION_NO)
);


--
-- �W���u���ʃe�[�u��
--
CREATE TABLE JOB_RESULT (
  REQUEST_NO VARCHAR(20),
  JOB_ID VARCHAR(20),
  JOB_STATE CHAR(1),
  END_CODE VARCHAR(5),
  REGISTER_TIME TIMESTAMP
);



COMMIT;
